name: build

on:
  workflow_dispatch:
    inputs:
      android:
        description: 'android'
        required: true
        type: boolean
      ios:
        description: 'ios'
        required: true
        type: boolean
      web:
        description: 'web'
        required: true
        type: boolean
      mac:
        description: 'mac'
        required: true
        type: boolean
      windows:
        description: 'windows'
        required: true
        type: boolean
      linux:
        description: 'linux'
        required: true
        type: boolean

jobs:
  build-android:
    if: ${{ github.event.inputs.android == 'true' }} 
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.0'
          channel: 'stable'
          cache: true
      - run: flutter pub get
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - run: flutter build apk
      - run: flutter build appbundle
      - uses: actions/upload-artifact@v3
        with:
          path: /Users/runner/work/my_ranking/my_ranking/build/
          retention-days: 15
  build-ios:
    if: ${{ github.event.inputs.ios == 'true' }} 
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0'
        channel: 'stable'
        cache: true
        architecture: x64
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - uses: actions/upload-artifact@v3
      with:
        path: /Users/runner/work/my_ranking/my_ranking/build/
        retention-days: 15
  build-web:
    if: ${{ github.event.inputs.web == 'true' }} 
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         flutter-version: '3.7.0'
         channel: 'stable'
         cache: true
     - run: flutter pub get
     - run: flutter build web
     - uses: actions/upload-artifact@v3
       with:
         path: /Users/runner/work/my_ranking/my_ranking/build/
         retention-days: 15
  build-windows:
   if: ${{ github.event.inputs.windows == 'true' }} 
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         flutter-version: '3.7.0'
         channel: 'stable'
         cache: true
     - run: flutter config --enable-windows-desktop
     - run: flutter build windows
     - uses: actions/upload-artifact@v3
       with:
         path: /Users/runner/work/my_ranking/my_ranking/build/
         retention-days: 15
  build-linux:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:  
         flutter-version: '3.7.0'
         channel: 'stable'
         cache: true
     - run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
     - run: flutter config --enable-linux-desktop
     - run: flutter build linux
     - uses: actions/upload-artifact@v3
       with:
         path: /Users/runner/work/my_ranking/my_ranking/build/
         retention-days: 15
  build-mac:
   if: ${{ github.event.inputs.mac == 'true' }} 
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         flutter-version: '3.7.0'
         channel: 'stable'
         cache: true
         architecture: x64
     - run: flutter config --enable-macos-desktop
     - run: flutter build macos
     - uses: actions/upload-artifact@v3
       with:
         path: /Users/runner/work/my_ranking/my_ranking/build/
         retention-days: 15
